name: Build Tweak for TrollFools

on:
  push:
    branches:
      - main
      - cryptokitsha256hook
  pull_request:
  workflow_dispatch:

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot rsync curl perl zip git libxml2 libtinfo6

      - name: Set up Theos Toolchain and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git "$THEOS"
          mkdir -p "$THEOS/toolchain"
          curl -sL https://github.com/L1ghtmann/llvm-project/releases/latest/download/iOSToolchain-x86_64.tar.xz | tar -xJ -C "$THEOS/toolchain"
          "$THEOS/bin/install-sdk" latest

      - name: Build deb Package
        run: make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CryptoKitSHA256Hook-deb
          path: packages/*.deb
